CREATE DATABASE IF NOT EXISTS twinparkos
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE twinparkos;

CREATE TABLE IF NOT EXISTS app_store (
  id VARCHAR(64) PRIMARY KEY,
  data LONGTEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
